# Generated by Django 4.1.6 on 2023-02-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingdetail",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
